# Site settings
title: 买女孩的小火柴
email: 664454335@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luckypia.github.io" # the base hostname & protocol for your site
twitter_username: lucky_bking
github_username:  LuckyPia
google_play: 'GDGX'
google_plus_com: '109485346959707049693'  # Community link
google_plus_per: '+GDGManagua'  #Personal link
facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Option 1
    link: www.luckypia.github.io
  option2:
    name: Option 2
    link: www.luckypia.github.io
  option3:
    name: Option 3
    link: www.luckypia.github.io

disqus: true
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
